name: Geometric Lib
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ubuntu_test:
      runs-on: ubuntu-latest
      steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.*
      - name: Test
        run: python -m unittest tests/test.py
  windows-test:
    runs-on: windows-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.*
      - name: Test
        run: python -m unittest tests/test.py
